name = "uv-notifier"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "sunsmart_subscriptions"
id = "46571c253dc84c999343751ea8f70ebb"

[triggers]
crons = ["*/10 * * * *", "0 0 * * *"]
